<!DOCTYPE html>
<html lang="ja-JP">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <meta http-equiv="Content-Language" content="ja-JP">
  <link rel="stylesheet" type="text/css" href="../../../style.css">
  <link rel="icon" type="image/png" href="../../../rurema.png">
  
  <title>module function Kernel.#lambda (Ruby 2.2.0)</title>
</head>
<body>

<p>
<a href="../../../doc/index.html">Ruby 2.2.0 リファレンスマニュアル</a>
&gt; <a href="../../../library/index.html">ライブラリ一覧</a>
&gt; <a href="../../../library/_builtin.html">組み込みライブラリ</a>
&gt; <a href="../../../class/-kernel.html">Kernelモジュール</a>
&gt; lambda

</p>


<h1>module function Kernel.#lambda</h1>
<dl class="methodlist">

<dt class="method-heading" id="M_LAMBDA"><code>proc { ... } -&gt; Proc</code><span class="permalink">[<a href="../../../method/-kernel/m/lambda.html">permalink</a>][<a href="http://docs.ruby-lang.org/en/2.2.0/Kernel.html#method-c-lambda">rdoc</a>]</span></dt>
<dt class="method-heading"><code>lambda { ... } -&gt; Proc</code></dt>
<dt class="method-heading"><code>proc -&gt; Proc</code></dt>
<dt class="method-heading"><code>lambda -&gt; Proc</code></dt>
<dd class="method-description">
<p>
与えられたブロックから手続きオブジェクト (<a href="../../../class/-proc.html">Proc</a> のインスタンス)
を生成して返します。<a href="../../../method/-proc/s/new.html">Proc.new</a> に近い働きをします。
</p>
<p>
ブロックが指定されなければ、呼び出し元のメソッドで指定されたブロック
を手続きオブジェクトとして返します。呼び出し元のメソッドがブロックなし
で呼ばれると <a href="../../../class/-argument-error.html">ArgumentError</a> 例外が発生します。
</p>
<p>
ただし、ブロックを指定しない呼び出しは推奨されていません。呼び出し元のメソッドで指定されたブロック
を得たい場合は明示的に &amp; 引数でうけるべきです。
</p>
<dl>
<dt>[EXCEPTION] ArgumentError:</dt>
<dd>
スタック上にブロックがないのにブロックを省略した呼び出しを行ったときに発生します。
</dd>
</dl>
<pre>
def foo &amp;block
  lambda(&amp;block)
end

it = foo{p 12}
it.call #=&gt; 12
</pre>
<p>
[SEE_ALSO] <a href="../../../class/-proc.html">Proc</a>,<a href="../../../method/-proc/s/new.html">Proc.new</a>
</p>
<h1 id='should_use_next'>手続きを中断して値を返す</h1>
<p>
手続きオブジェクトを中断して、呼出し元(呼び出しブロックでは yield、それ以外では <a href="../../../method/-proc/i/call.html">Proc#call</a>)
へジャンプし値を返すには next を使います。break や return ではありません。
</p>
<p>
例:
</p>
<pre>
 def foo
   f = Proc.new{
     next 1
     2
   }
 end

p foo().call       #=&gt; 1
</pre>
<h1 id='block'>Proc オブジェクトをブロック付きメソッド呼び出しに使う</h1>
<p>
ブロック付きメソッドに対して Proc オブジェクトを `&amp;' を指定して渡すと
呼び出しブロックのように動作します。
しかし、厳密には以下の違いがあります
これらは、Proc オブジェクトが呼び出しブロックとして振舞う際の制限です。
</p>
<pre>
# 問題なし
(1..5).each { break }

# LocalJumpError が発生します。
pr = Proc.new { break }
(1..5).each(&amp;pr)
</pre>
<h1 id='lambda_proc'>lambda と proc と Proc.new とイテレータの違い</h1>
<p>
<a href="../../../method/-kernel/m/lambda.html">Kernel.#lambda</a> と <a href="../../../method/-proc/s/new.html">Proc.new</a> はどちらも <a href="../../../class/-proc.html">Proc</a> クラスのインスタンス(手続きオブジェクト)を生成しますが、
生成された手続きオブジェクトはいくつかの場面で挙動が異なります。 lambda の生成する手続きオブジェクトのほうが
よりメソッドに近い働きをするように設計されています。
</p>
<p>
<a href="../../../method/-kernel/m/proc.html">Kernel.#proc</a> は Proc.new と同じになります。
引数に &amp; を付けることで手続きオブジェクト化したブロックは、Proc.new で生成されたそれと
同じにように振る舞います。
</p>
<h2 >引数の扱い</h2>
<p>
lambda のほうがより厳密です。引数の数が違っていると（メソッドのように）エラーになります。
Proc.new は引数を多重代入に近い扱い方をします。
</p>
<p>
例:
</p>
<pre>
b1 = Proc.new{|a,b,c|
  p a,b,c
}
b1.call(2, 4)
#=&gt; 2
    4
    nil

b2 = lambda{|a,b,c|
  p a,b,c
}
b2.call(2, 4)
#=&gt; wrong number of arguments (2 for 3) (ArgumentError)
</pre>
<p>
<a href="../../../doc/spec=2fcall.html#block_arg">メソッド呼び出し(super・ブロック付き・yield)/ブロックパラメータの挙動</a> も参照してください。
</p>
<h2 >ジャンプ構文の挙動の違い</h2>
<p>
return と break は、lambda と Proc.new では挙動が異なります。
例えば return を行った場合、lambda では手続きオブジェクト自身を抜けますが、
Proc.new では手続きオブジェクトを囲むメソッドを抜けます。
</p>
<p>
例:
</p>
<pre>
def foo
  f = Proc.new { return :foo }
  f.call
  return
end

def bar
  f = lambda { return :bar }
  f.call
  return
end

def h
  yield
end

def hoge
  h{ return :hoge }
  nil
end

p foo()  #=&gt; :foo
p bar()  #=&gt; nil
p hoge() #=&gt; :hoge
</pre>
<p>
以下の表は、手続きオブジェクトの実行を上の例と同じように、手続きオブジェクトが定義されたのと
同じメソッド内で行った場合の結果です。
</p>
<pre>
               return                          next                        break
Proc.new   メソッドを抜ける            手続きオブジェクトを抜ける   例外が発生する
proc       メソッドを抜ける            手続きオブジェクトを抜ける   例外が発生する
lambda     手続きオブジェクトを抜ける  手続きオブジェクトを抜ける   手続きオブジェクトを抜ける
イテレータ メソッドを抜ける            手続きオブジェクトを抜ける   メソッドを抜ける
</pre>
<h1 id='orphan'>orphan な手続きオブジェクトの挙動</h1>
<p>
Proc を生成したメソッドから脱出した後、手続きオブジェクトからの
return, break
は例外 <a href="../../../class/-local-jump-error.html">LocalJumpError</a> を発生させます。
ただし、上でも説明した通り lambda で生成した手続きオブジェクトはメソッドと同じように振る舞う
ことを意図されているため、例外 <a href="../../../class/-local-jump-error.html">LocalJumpError</a> は発生しません。
</p>
<p>
例:
</p>
<pre>
def foo
  Proc.new { return }
end

foo.call
# =&gt; in `call': return from proc-closure (LocalJumpError)
</pre>
<p>
以下の表は、手続きオブジェクトの実行を上の例と同じように、手続きオブジェクトが定義されたメソッドを
脱出してから行った場合の結果です。
</p>
<pre>
               return                          next                        break
Proc.new   例外が発生する              手続きオブジェクトを抜ける   例外が発生する
proc       例外が発生する              手続きオブジェクトを抜ける   例外が発生する
lambda     手続きオブジェクトを抜ける  手続きオブジェクトを抜ける   手続きオブジェクトを抜ける
</pre>
</dd>


</dl>


<div id="footer">
  <a rel="license" href="https://creativecommons.org/licenses/by/3.0/">
    <img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/3.0/88x31.png" />
  </a>
</div>
</body>
</html>
