<!DOCTYPE html>
<html lang="ja-JP">
<head>

<meta name="robots" content="noindex">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="../style.css">
<link rel="stylesheet" href="../syntax-highlight.css">
<link rel="icon" type="image/png" href="../rurema.png">

<title>class SystemCallError (Ruby 3.1.2 リファレンスマニュアル)</title>
<meta name="description" content="Ruby の実装に用いられているシステムコールまたは一部の C 言語関数が失敗した時に発生する例外です。
システムコールの失敗した原因を表すエラーコードを保持します。">
<script src="../script.js"></script>
</head>
<body>


<header>
  <nav>
    <ol class="inline-breadcrumb-list">
      <li>
        <a href="../doc/index.html">Ruby 3.1.2 リファレンスマニュアル</a>
      </li>
      <li>
        <a href="../library/index.html">ライブラリ一覧</a>
      </li>
      <li>
        <a href="../library/_builtin.html">組み込みライブラリ</a>
      </li>
      <li>
        SystemCallErrorクラス
      </li>
    </ol>
  </nav>

<h1>class SystemCallError</h1>
</header>

<main>



  <nav>
    クラス・モジュールの継承リスト:
    <ol class="inline-ancestors-list">
      
        <li>
          <a href="../class/-basic-object.html">BasicObject</a>
        </li>
        
      
        <li>
          <a href="../class/-kernel.html">Kernel</a>
        </li>
        
      
        <li>
          <a href="../class/-object.html">Object</a>
        </li>
        
      
        <li>
          <a href="../class/-exception.html">Exception</a>
        </li>
        
      
        <li>
          <a href="../class/-standard-error.html">StandardError</a>
        </li>
        
      
      <li>
        SystemCallError
      </li>
    </ol>
  </nav>











<h2>要約</h2>
<p>
Ruby の実装に用いられているシステムコールまたは一部の C 言語関数が失敗した時に発生する例外です。システムコールの失敗した原因を表すエラーコードを保持します。
</p>
<p>
多くの場合、実際には SystemCallError そのものではなくサブクラスである <a href="../class/-errno=3a=3a-e-x-x-x.html">Errno::EXXX</a> (XXX はエラーコードの値によって異なる。システム定義のエラー名と同じ名前) が発生します。詳しくは <a href="../class/-errno=3a=3a-e-x-x-x.html">Errno::EXXX</a> を参照してください。
</p>



<h2>目次</h2>
<dl>

<dt>特異メソッド</dt>
<dd>
<ul class="class-toc">

<li><a href="#S_--3D--3D--3D">===</a></li>

<li><a href="#S_NEW">new</a></li>

</ul>
</dd>

<dt>インスタンスメソッド</dt>
<dd>
<ul class="class-toc">

<li><a href="#I_ERRNO">errno</a></li>

</ul>
</dd>

</dl>




  <h2>継承しているメソッド</h2>
<dl>
  
<dt>Exceptionから継承しているメソッド</dt>
<dd>
  <ul class="class-toc">
    
      <li><a href="../method/-exception/i/=3d=3d.html">==</a></li>
      
    
      <li><a href="../method/-exception/i/backtrace.html">backtrace</a></li>
      
    
      <li><a href="../method/-exception/i/backtrace_locations.html">backtrace_locations</a></li>
      
    
      <li><a href="../method/-exception/i/cause.html">cause</a></li>
      
    
      <li><a href="../method/-exception/i/exception.html">exception</a></li>
      
    
      <li><a href="../method/-exception/i/full_message.html">full_message</a></li>
      
    
      <li><a href="../method/-exception/i/inspect.html">inspect</a></li>
      
    
      <li><a href="../method/-exception/i/message.html">message</a></li>
      
    
      <li><a href="../method/-exception/i/set_backtrace.html">set_backtrace</a></li>
      
    
      <li><a href="../method/-exception/i/message.html">to_s</a></li>
      
    
  </ul>
</dd>

</dl>


<h2>特異メソッド</h2>
<dl>

<dt class="method-heading" id="S_--3D--3D--3D"><code>self === other -&gt; bool</code><span class="permalink">[<a href="../method/-system-call-error/s/=3d=3d=3d.html">permalink</a>][<a href="https://docs.ruby-lang.org/en/3.1.2/SystemCallError.html#method-c-3D-3D-3D">rdoc</a>]</span></dt>
<dd class="method-description">
<p>
other が SystemCallError のサブクラスのインスタンスで、かつ、other.errno の値が self::Errno と同じ場合に真を返します。そうでない場合は偽を返します。
</p>
<p>
従って、特に other が self.kind_of?(other) である場合には <a href="../method/-module/i/=3d=3d=3d.html">Module#===</a> と同様に真を返します。その他に、 Errno::EXXX::Errno == Errno::EYYY::Errno である場合にも Errno::EXXX == Errno::EYYY.new は真を返します。
</p>
<p>
エラー名は異なるがエラーコードは同じであるような Errno::EXXX 例外をまとめて捕捉するために <a href="../method/-module/i/=3d=3d=3d.html">Module#===</a> を上書きしていました。しかし、Ruby 1.8 のリリース時点では同じ errno 値を持つクラスは一つしか作られないようになりました。そのため現在はこのメソッドは実質上 <a href="../method/-module/i/=3d=3d=3d.html">Module#===</a> と同じ意味しかありません。
</p>
<dl>
<dt class='method-param'>[PARAM] other:</dt>
<dd>
任意のオブジェクト
</dd>
</dl>
<p>
例
</p>
<pre>
p Errno::EAGAIN::Errno
p Errno::EWOULDBLOCK::Errno
begin
  raise Errno::EAGAIN, &quot;pseudo error&quot;
rescue Errno::EWOULDBLOCK
  p $!
end

# =&gt; 11
     11
     #&lt;Errno::EAGAIN: pseudo error&gt;
</pre>
</dd>


<dt class="method-heading" id="S_NEW"><code>new(error_message) -&gt; SystemCallError</code><span class="permalink">[<a href="../method/-system-call-error/s/new.html">permalink</a>][<a href="https://docs.ruby-lang.org/en/3.1.2/SystemCallError.html#method-c-new">rdoc</a>]</span></dt>
<dd class="method-description">
<p>
SystemCallError オブジェクトを生成して返します。
</p>
<dl>
<dt class='method-param'>[PARAM] error_message:</dt>
<dd>
エラーメッセージを表す文字列
</dd>
</dl>
<p>
例:
</p>
<pre>
p SystemCallError.new(&quot;message&quot;)
    # =&gt; #&lt;SystemCallError: unknown error - message&gt;
</pre>
</dd>
<dt class="method-heading" id="S_NEW"><code>new(error_message, errno) -&gt; SystemCallError</code><span class="permalink">[<a href="../method/-system-call-error/s/new.html">permalink</a>][<a href="https://docs.ruby-lang.org/en/3.1.2/SystemCallError.html#method-c-new">rdoc</a>]</span></dt>
<dt class="method-heading"><code>new(errno) -&gt; SystemCallError</code></dt>
<dd class="method-description">
<p>
整数 errno に対応する <a href="../class/-errno=3a=3a-e-x-x-x.html">Errno::EXXX</a> オブジェクトを生成して返します。
</p>
<p>
整数 errno をシステムコールで発生したエラーの原因を示すコードであると解釈し、対応する例外クラスのインスタンスを生成して返します。
</p>
<p>
生成されるオブジェクトは SystemCallError の直接のインスタンスではなく、サブクラスのインスタンスです。それらのサブクラスは <a href="../class/-errno.html">Errno</a> モジュール内に定義されています。対応するサブクラスが存在しないコードを与えた場合には、 SystemCallError の直接のインスタンスが生成されます。
</p>
<p>
エラーコードの取り得る値および意味はシステムに依存します。詳しくは <a href="../class/-errno=3a=3a-e-x-x-x.html">Errno::EXXX</a> を参照してください。
</p>
<dl>
<dt class='method-param'>[PARAM] error_message:</dt>
<dd>
エラーメッセージを表す文字列
</dd>
<dt class='method-param'>[PARAM] errno:</dt>
<dd>
システム依存のエラーコード
</dd>
<dt>[EXCEPTION] TypeError:</dt>
<dd>
errno を整数に変換できないときに発生します。
</dd>
</dl>
<p>
例:
</p>
<pre>
p SystemCallError.new(&quot;message&quot;, 2)
    # =&gt; #&lt;Errno::ENOENT: No such file or directory - message&gt;
p SystemCallError.new(2)
    # =&gt; #&lt;Errno::ENOENT: No such file or directory&gt;
p SystemCallError.new(256)
    # =&gt; #&lt;SystemCallError: Unknown error 256&gt;
</pre>
</dd>


</dl>

<h2>インスタンスメソッド</h2>
<dl>

<dt class="method-heading" id="I_ERRNO"><code>errno -&gt; Integer | nil</code><span class="permalink">[<a href="../method/-system-call-error/i/errno.html">permalink</a>][<a href="https://docs.ruby-lang.org/en/3.1.2/SystemCallError.html#method-i-errno">rdoc</a>]</span></dt>
<dd class="method-description">
<p>
レシーバに対応するシステム依存のエラーコードを返します。
</p>
<p>
エラーコードを渡さない形式で生成した場合は nil を返します。
</p>
<pre>
begin
  raise Errno::ENOENT
rescue Errno::ENOENT =&gt; err
  p err.errno                 # =&gt; 2
  p Errno::ENOENT::Errno      # =&gt; 2
end

begin
  raise SystemCallError, 'message'
rescue SystemCallError =&gt; err
  p err.errno                 # =&gt; nil
end
</pre>
<p>
なお、例外を発生させずにエラーコードを得るには、
<a href="../method/-errno=3a=3a-e-x-x-x/c/-errno.html">Errno::EXXX::Errno</a> 定数を使います。
</p>
</dd>


</dl>

</main>

<footer id="footer">
  <a rel="license" href="https://creativecommons.org/licenses/by/3.0/">
    <img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/3.0/88x31.png" />
  </a>

  <a href="https://github.com/rurema/doctree/issues/new" id="feedback-link">フィードバックを送る</a>
  
  <script>if (window.URLSearchParams) { document.getElementById("feedback-link").search = new URLSearchParams({'body': document.location}); }</script>
</footer>
</body>
</html>
